name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  DOTNET_VERSION: "9.x"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: DevHabit

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build DevHabit.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test DevHabit.sln --configuration Release --no-build --no-restore --verbosity normal --filter "FullyQualifiedName~Tests"
      
      - name: Publish
        run: dotnet publish DevHabit.sln --configuration Release --no-build --no-restore --output ./publish